insert into ramo_atividade (id, descricao) values (1, 'Distribuição de alimentos');
insert into ramo_atividade (id, descricao) values (2, 'Telecomunicações');
insert into ramo_atividade (id, descricao) values (3, 'Vestuário');
insert into ramo_atividade (id, descricao) values (4, 'Lavanderia');
insert into ramo_atividade (id, descricao) values (5, 'Gráfica');
insert into ramo_atividade (id, descricao) values (6, 'Mecânica');
insert into ramo_atividade (id, descricao) values (7, 'Turismo');
insert into ramo_atividade (id, descricao) values (8, 'Saúde');
insert into ramo_atividade (id, descricao) values (9, 'Educação');
insert into ramo_atividade (id, descricao) values (10, 'Lazer');
insert into ramo_atividade (id, descricao) values (11, 'Energias Renováveis')
insert into ramo_atividade (id, descricao) values (12, 'Consultoria Empresarial');
insert into ramo_atividade (id, descricao) values (13, 'Segurança Eletrônica');
insert into ramo_atividade (id, descricao) values (14, 'Publicidade e Propaganda');
insert into ramo_atividade (id, descricao) values (15, 'Imobiliária');
insert into ramo_atividade (id, descricao) values (16, 'Design Gráfico');
insert into ramo_atividade (id, descricao) values (17, 'Comércio Atacadista');
insert into ramo_atividade (id, descricao) values (18, 'Indústria Automotiva');
insert into ramo_atividade (id, descricao) values (19, 'Comércio de Eletrônicos');

insert into empresa (cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ('70.311.193/0001-87', 'Mercado do João', 'João Mercado e Distribuidor de Alimentos Ltda', 'LTDA', '2009-03-02', 1);
insert into empresa (cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ('52.822.994/0001-25', 'Fale Mais', 'Fale Mais Telecom S.A.', 'SA', '1997-12-10', 2);
insert into empresa (cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ('41.952.519/0001-57', 'Maria de Souza da Silva', 'Maria de Souza da Silva', 'MEI', '2014-10-15', 3);
insert into empresa (cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ('16.134.777/0001-89', 'Gomes Inovação', 'José Fernando Gomes EIRELI ME', 'EIRELI', '2009-03-02', 4);
insert into empresa (cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ('12.345.678/0001-01', 'Distribuidora Alimentos ABC', 'ABC Distribuidora de Alimentos LTDA', 'LTDA', '2005-05-15', 1);
insert into empresa (cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ('23.456.789/0001-02', 'Gourmet & Sabor', 'Gourmet & Sabor Distribuidora de Alimentos EIRELI', 'EIRELI', '2010-10-20', 1);
insert into empresa (cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ('34.567.890/0001-03', 'Mercado da Praia', 'Mercado da Praia Comércio de Alimentos Ltda', 'LTDA', '2007-07-01', 1);
insert into empresa (cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ('45.678.901/0001-04', 'TecnoCom', 'TecnoCom Telecomunicações S.A.', 'SA', '1998-08-12', 2);
insert into empresa (cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ('56.789.012/0001-05', 'NetFone', 'NetFone Comunicações LTDA', 'LTDA', '2003-04-25', 2);
insert into empresa (cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ('58.720.961/0001-50', 'Gráfica Printex', 'Printex Gráfica e Editora Ltda', 'LTDA', '2005-08-12', 5);
insert into empresa (cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ('23.304.486/0001-09', 'Mecânica Forte', 'Forte Mecânica e Manutenção Automotiva Ltda', 'LTDA', '1998-06-21', 6);
insert into empresa (cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ('09.788.738/0001-70', 'Viaje Bem', 'Viaje Bem Turismo e Viagens S.A.', 'SA', '2003-05-15', 7);
insert into empresa (cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ('94.501.242/0001-01', 'Clinica Vida Nova', 'Clínica Vida Nova de Saúde e Bem-Estar Ltda', 'LTDA', '2012-02-20', 8);
insert into empresa (cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ('11.553.885/0001-63', 'Escola Saber Mais', 'Escola Saber Mais de Educação Infantil e Fundamental Ltda', 'LTDA', '2000-10-05', 9);
insert into empresa (cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ('40.547.394/0001-50', 'Cinemark', 'Cinemark Brasil S.A.', 'SA', '1999-07-07', 10);
insert into empresa (cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ('35.215.934/0001-09', 'EcoEnergia', 'EcoEnergia Energias Renováveis Ltda', 'LTDA', '2015-04-18', 11);
insert into empresa (cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ('27.169.412/0001-48', 'Consultoria Top', 'Top Consultoria Empresarial S.A.', 'SA', '2007-11-03', 12);
insert into empresa (cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ('31.575.438/0001-61', 'SegurAlarme', 'SegurAlarme Segurança Eletrônica Ltda', 'LTDA', '2010-09-22', 13);
insert into empresa (cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ('49.886.744/0001-92', 'Agência Full', 'Full Publicidade e Propaganda Ltda', 'LTDA', '2001-08-12', 14);
insert into empresa (cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ('07.353.609/0001-39', 'Copymax', 'Copymax Gráfica e Editora Ltda', 'LTDA', '1998-05-12', 5);
insert into empresa (cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ('71.276.508/0001-31', 'AutoMec', 'AutoMec Mecânica de Veículos Ltda', 'LTDA', '2005-08-28', 6);
insert into empresa (cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ('22.154.841/0001-03', 'Viajar Feliz', 'Viajar Feliz Agência de Turismo Ltda', 'LTDA', '2010-12-20', 7);
insert into empresa (cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ('27.913.220/0001-07', 'Clínica da Saúde', 'Clínica da Saúde Ltda', 'LTDA', '2000-07-10', 8);
insert into empresa (cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ('12.037.286/0001-28', 'Educar+', 'Educar+ Instituto de Ensino Ltda', 'LTDA', '2015-09-22', 9);
insert into empresa (cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ('61.634.408/0001-08', 'Vida Leve', 'Vida Leve Centro de Lazer e Entretenimento Ltda', 'LTDA', '2002-02-18', 10);
insert into empresa (cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ('78.446.947/0001-04', 'EcoEnergia', 'EcoEnergia Energias Renováveis S.A.', 'SA', '2011-05-30', 11);
insert into empresa (cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ('14.796.583/0001-09', 'ConsultoriaPro', 'ConsultoriaPro Consultoria Empresarial Ltda', 'LTDA', '2005-11-14', 12);
insert into empresa (cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ('39.114.191/0001-40', 'SeguraNet', 'SeguraNet Segurança Eletrônica Ltda', 'LTDA', '2012-08-05', 13);
insert into empresa (cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values ('03.815.872/0001-22', 'Publicidade Top', 'Publicidade Top Agência de Publicidade e Propaganda', 'MEI', '2004-08-05', 14);